### ISSUE TITLE
Managing package versions

### ISSUE THREAD

**Issue by Titaniumtown** [moonman/MyPKGBUILDs#4]
Do you think that you should make a pkgbuild for each branch. ex: linux-raspberrypi4-4.x, linux-raspberrypi4-5.4.x, etc.

It would be easier to manage.

Just a thought.

**Comment by Titaniumtown** [comment]
It would be so much easier to manage my repo like that.

**Comment by Titaniumtown** [comment]
would that be something you would be interested in doing @moonman?

**Comment by moonman** [comment]
Nope.  There is one main package for kernel: linux-raspberrypi4 which represents whatever Kevin picks for the main kernel for the 32-bit side. linux-raspberrypi4-latest is just whatever latest is available from rpi github repo. I build it for fun, and it may not be as useful to people. because it may have bugs etc, bad untested patches etc. You can fork my repo and do your own thing if you wish, however. Like usual, you just change my name to a contributor, and make yourself a maintainer.

**Comment by Titaniumtown** [comment]
Ok, thanks @moonman!
